version: '3.9'

services:
  server:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://db:27017/rating
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000'
    networks:
      - app-network

  db:
    image: mongo:latest
    restart: always
    container_name: MONGODB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge